### ISSUE TITLE
Join with password does not work on Ubuntu 18.04

### ISSUE THREAD

**Issue by Filgr** [walkamongus/realmd#55]
Ubuntu 18.04 does not properly join domain. I think computer name needs to be handled the same way as 16.04:
```
if $::operatingsystem == 'Ubuntu' and $facts['os']['distro']['codename']  == 'xenial' {
    $_computer_name_arg  = ''
}
```

**Comment by thorpj** [comment]
Testing fix on Ubuntu 18.04.1

These dependencies should be installed by this module

`Notice: /Stage[main]/Realmd::Join::Password/Exec[realm_join_with_password]/returns: Password for Administrator: See: journalctl REALMD_OPERATION=r3994.2803`

`Notice: /Stage[main]/Realmd::Join::Password/Exec[realm_join_with_password]/returns: realm: Couldn't join realm: Necessary packages are not installed: sssd-tools sssd libnss-sss libpam-sss adcli
`

`Error: '/usr/libexec/realm_join_with_password realm join <DOMAIN/obscured> --unattended --user=Administrator' returned 1 instead of one of [0]`

`Error: /Stage[main]/Realmd::Join::Password/Exec[realm_join_with_password]/returns: change from 'notrun' to ['0'] failed: '/usr/libexec/realm_join_with_password realm join <DOMAIN/obscured> --unattended --user=Administrator' returned 1 instead of one of [0]`

EDIT: I'm not actually convinced this is related to this issue.
That said, I will leave this here. The workaround was to `apt install packagekit`, so that realmd can handle the missing dependencies. 

It should be noticed that all the _missing_ packages were installed.
